#!/usr/bin/env bash
set -euo pipefail

# vigil-report.sh — Full wallet security report
# Usage: ./vigil-report.sh <wallet_address> [chain]

WALLET="${1:?Usage: vigil-report.sh <wallet_address> [chain]}"
CHAIN="${2:-base}"
API_BASE="${VIGIL_API:-https://api.bankr.bot/vigil}"

echo "🛡️  VIGIL Security Report"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Wallet: $WALLET"
echo "  Chain:  $CHAIN"
echo "  Time:   $(date -u '+%Y-%m-%d %H:%M UTC')"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

RESPONSE=$(curl -s -f "$API_BASE/report?wallet=$WALLET&chain=$CHAIN" \
  -H "Accept: application/json" \
  ${BANKR_API_KEY:+-H "Authorization: Bearer $BANKR_API_KEY"}) || {
  echo "Error: API request failed" >&2
  exit 1
}

OVERALL=$(echo "$RESPONSE" | jq -r '.overall_score')
RISK=$(echo "$RESPONSE" | jq -r '.risk_level')

case "$RISK" in
  critical) ICON="🔴" ;;
  high)     ICON="🟠" ;;
  medium)   ICON="🟡" ;;
  low)      ICON="🟢" ;;
  safe)     ICON="✅" ;;
esac

echo "📊 Overall Security Score: $OVERALL/100 $ICON"
echo ""

# Approvals summary
echo "━━━ Approvals ━━━"
echo "  Total:     $(echo "$RESPONSE" | jq '.approvals.total')"
echo "  Critical:  $(echo "$RESPONSE" | jq '.approvals.critical')"
echo "  High:      $(echo "$RESPONSE" | jq '.approvals.high')"
echo "  Unlimited: $(echo "$RESPONSE" | jq '.approvals.unlimited')"
echo ""

# Approve over $1000
HIGH_VALUE=$(echo "$RESPONSE" | jq '.approvals.high_value_count')
if [ "$HIGH_VALUE" -gt 0 ]; then
  echo "  ⚠️  $HIGH_VALUE approvals over \$1000 value at risk"
  echo ""
fi

# Interacted tokens
echo "━━━ Token Interactions ━━━"
echo "  Tokens Held:     $(echo "$RESPONSE" | jq '.tokens.held')"
echo "  Tokens Traded:   $(echo "$RESPONSE" | jq '.tokens.traded')"
echo "  Scam Tokens:     $(echo "$RESPONSE" | jq '.tokens.scam_flagged')"
echo ""

# Scam interaction history
SCAM_COUNT=$(echo "$RESPONSE" | jq '.scam_interactions | length')
if [ "$SCAM_COUNT" -gt 0 ]; then
  echo "━━━ Scam Interactions ━━━"
  echo "$RESPONSE" | jq -r '.scam_interactions[] | 
    "  🔴 \(.token_name) (\(.token_address[0:10]...)) — \(.type) on \(.date)"'
  echo ""
fi

# Top risky approvals (detail)
echo "━━━ Top Risky Approvals ━━━"
echo "$RESPONSE" | jq -r '.top_risks[:5][] | 
  "  \(if .risk == "critical" then "🔴" elif .risk == "high" then "🟠" else "🟡" end) \(.token_symbol) → \(.spender_name // .spender_address[0:16])\n     Amount: \(if .amount == "unlimited" then "UNLIMITED ⚠️" else .amount end)"'
echo ""

# Recommendations
echo "━━━ Recommendations ━━━"
echo "$RESPONSE" | jq -r '.recommendations[] | "  \(if .priority == "critical" then "🔴" elif .priority == "high" then "🟠" else "🟡" end) \(.action): \(.detail)"'
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🛡️ Report generated by VIGIL"
echo "  Run vigil-batch-revoke.sh to fix all risky approvals"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
